{
     "ci": false,
     "branches": ["main"],
     "repositoryUrl": "https://github.com/jmunta-tlx/yarn-project-ci",
     "debug": "true",
     "plugins": [
          ["@semantic-release/npm", {
            "npmPublish": false,
          }],
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        [
            "@semantic-release/changelog",
            {
                "changelogFile": "CHANGELOG.md",
                "changelogTitle": "# Semantic Versioning Changelog"
            }
        ],
        [
            "@semantic-release/exec",
            {
                "prepareCmd": "./prepare-release.sh ${nextRelease.version}"
            }
        ],
        [
            "@semantic-release/git",
            {
                "assets": [
                    "CHANGELOG.md",
                    "package.json"
                ]
            }
        ],
        [
            "@semantic-release/github",
            {
                "assets": [
                    {
                        "path": "release/**"
                    }
                ]
            }
        ]
    ]
}